const test1ttttt := 2*5+1+"hello world"
var temp :int
const test2 := -1.111
const test2 :int := 1
const test3 := 12.3
const t := -test2 + test3
const test4 := not true and false or true + 1 * 0.5 + "strssss""s1111111234" 
const test :real := 23.33
const test5 := "tt"
var test6 := 878
var test7 := 1.1
var test8 := "hello"
var test9 := true
var test10 :int := 100
var test11 :string 
var test12 :array 0 . . 100 of int
var i:int
var j:int


function test13(input : int, arr : 0 . . 100 of bool): int
    const test1 := 11.11
    const test2 := arr[1]
    const test3 := i + j
    const test4 := test1 + test2
end aaa

function add(a : int, b : int): int
    var c :int := 5
    var d :int := 6
    return
end add


const test15 :string := "123"""

test6 := add(i, j)

aa := 1000
test5 := 5
test6 := "123"
get test7
get test5
get aa

if true then 
    const test1 := 11.11
    var test8 := "hello"
else
    const test2 := 11.11
    var test3 := "hello"
end if

loop
    const test4 := 11.11
    const test6 :real := 11.11
    begin
        const test5 := 12.12
    end
    exit when test4 = test6
end loop

if true then 
    const test7 := 11.11
    var test6 := "hello"
end if 

for i : 0 . . 100
    var j :int
end for

for decreasing j : 100 . . 0
    var k :int
end for
